plugins {
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'java'
}

group = 'nextstep'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

dependencies {
    // Spring MVC 기반 웹 애플리케이션 개발용
    // @RestController, @RequestMapping, 내장 Tomcat, JSON 변환 등이 포함됨
    implementation 'org.springframework.boot:spring-boot-starter-web'

    implementation 'org.springframework.boot:spring-boot-starter-validation' // 요청 값 검증용

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa' // Spring Data JPA 사용용
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'

    // Lombok 사용용
    // @Getter, @NoArgsConstructor, @RequiredArgsConstructor 등을 컴파일 시점에 코드 생성
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // MySQL 연결 드라이버
    // 애플리케이션 실행 시 MySQL DB에 연결하기 위해 필요
    runtimeOnly 'com.mysql:mysql-connector-j'
    runtimeOnly 'com.h2database:h2' // 테스트나 로컬 간단 실행용 DB로 사용

    // Spring Boot 테스트용
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'io.rest-assured:rest-assured:5.3.1' // API 테스트용

    // 테스트 코드에서도 Lombok 사용하기 위한 설정
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
}

test {
    useJUnitPlatform()
}
