services:
  mysql:
    image: mysql:8.0
    container_name: blog-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog
    ports:
      - "3306:3306"
    volumes:
      - blog-mysql-data:/var/lib/mysql

volumes:
  blog-mysql-data: